=== dyyarosh/HW/t#19/src/main/resources/Items.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.epam.tc.com/notes" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="items" type="not:itemsType" xmlns:not="http://www.epam.tc.com/notes"/>
  <xs:complexType name="ItemType">
    <xs:sequence>
      <xs:element name="Id" type="xs:integer">
      </xs:element>
      <xs:element name="OwnerId" type="xs:integer">
      </xs:element>
      <xs:element name="Name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:whiteSpace value="preserve"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="Price" type="xs:double">
      </xs:element>
      <xs:element name="Status">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="Available|Rented"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="itemsType">
    <xs:sequence>
      <xs:element type="not:ItemType" name="Item" maxOccurs="unbounded" minOccurs="0" xmlns:not="http://www.epam.tc.com/notes"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== dyyarosh/HW/t#19/src/main/resources/Items.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tc:items xmlns:tc="http://www.epam.tc.com/notes"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.epam.tc.com/Items Items.xsd">


	<tc:Item>
		<tc:Id>1</tc:Id>
		<tc:OwnerId>-1</tc:OwnerId>
		<tc:Name>Football helmet</tc:Name>
		<tc:Price>20.0</tc:Price>
		<tc:Status>Available</tc:Status>
	</tc:Item>
	<tc:Item>
		<tc:Id>2</tc:Id>
		<tc:OwnerId>-1</tc:OwnerId>
		<tc:Name>Shoulder pads</tc:Name>
		<tc:Price>11.1</tc:Price>
		<tc:Status>Available</tc:Status>
	</tc:Item>
		<tc:Item>
		<tc:Id>3</tc:Id>
		<tc:OwnerId>-1</tc:OwnerId>
		<tc:Name>Mouthguards</tc:Name>
		<tc:Price>5.0</tc:Price>
		<tc:Status>Available</tc:Status>
	</tc:Item>
	<tc:Item>
		<tc:Id>4</tc:Id>
		<tc:OwnerId>2001</tc:OwnerId>
		<tc:Name>Ski suits</tc:Name>
		<tc:Price>99.9</tc:Price>
		<tc:Status>Rented</tc:Status>
	</tc:Item>
	<tc:Item>
		<tc:Id>5</tc:Id>
		<tc:OwnerId>2002</tc:OwnerId>
		<tc:Name>Elbow pads</tc:Name>
		<tc:Price>25.3</tc:Price>
		<tc:Status>Rented</tc:Status>
	</tc:Item>
</tc:items>
